export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_AUTH_ERROR = 'LOGIN_AUTH_ERROR';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';
